- mdn/scrape.py
- mdn/tests/test_scrape.py
- Ignore paragraph/s with \&nbsp; or empty after Compatibility Table
> fix bug 1132781

- .gitignore
- tools/common.py
- tools/import_mdn.py
- tools/load_spec_data.py
- tools/mirror_mdn_features.py
Florian Sholtz and the MDN team have reduced a lot of the [importer issues](https://browsercompat.herokuapp.com/importer/issues), and have requested a re-scrape of MDN to see if new content has additional issues.  This PR includes tool improvements that will help the process.  This code has **not** been run against https://browsercompat.herokuapp.com, since we're trying to do code reviews before "production" pushes.
* Fix [bug 1182542](https://bugzilla.mozilla.org/show_bug.cgi?id=1182542) - Use recursive calls to ``$children`` to discover MDN URLs more than 5 levels deep.
* Handle various error conditions with ``$children`` API
* Make it easy to get fresh content with ``--no-cache``
* Re-scrape MDN with ``import_mdn.py``.
If you want to run this locally:
* Setup browsercompat project
* …
> fix bug 1182542 - Scrape deeply nested MDN pages, other fixes

- mdn/models.py
- mdn/tasks.py
- mdn/tests/test_models.py
- mdn/tests/test_tasks.py
- mdn/tests/test_views.py
- mdn/views.py
- tools/client.py
- tools/import_mdn.py
- webplatformcompat/tests/test_validators.py
- webplatformcompat/validators.py
- wpcsite/settings.py
This fixes [bug 1194565](https://bugzilla.mozilla.org/show_bug.cgi?id=1194565), a 500 error when the importer tries to import a URL that has been turned into a zone URL.  https://browsercompat.herokuapp.com/importer/6247, the import for https://developer.mozilla.org/en-US/docs/Web/Apps/Design/Patterns/Entry_sheet, shows this error when you reset the page.
Firefox OS 1.0.1 is loaded in the browsercompat-data set, but `tools/upload_data.py` couldn't load it because the API was rejecting it.  This required fixing [bug 1134584](https://bugzilla.mozilla.org/show_bug.cgi?id=1134584) as well. 
To test:
1. Start with a fresh database
2. `./manage.py syncdb`, add a superuser
3. Checkout [browsercompat-data](https://github.com/mdn/browsercompat-data)
4. Run the server: `DJANGO_DEBUG=1 ./manage.py …
> fix bug 1194565 and bug 1134584 - Importer issues

- mdn/compatibility.py
- mdn/kumascript.py
- mdn/tests/test_kumascript.py
- mdn/tests/test_utils.py
- mdn/utils.py
Generalize parsing of version numbers from ``{{Compat*}}`` macros such as ``{{CompatChrome}}``, ``{{CompatSafari}}``, etc., and add support for missing macros.  This will resolve over 1600 [unknown_kumascript](https://browsercompat.herokuapp.com/importer/issues/unknown_kumascript) issues in the new importer.
> bug 1181140 - Handle {{Compat*}} macros

- mdn/kumascript.py
- mdn/tests/test_specifications.py
Convert {{SpecName('Name')}} to 'specification Name' in the specification description cell.  Fixes over 400 [unexpected_kumascript](https://browsercompat.herokuapp.com/importer/issues/unexpected_kumascript) issues.
> fix bug 1198912 - Allow {{SpecName}} in spec desc

- mdn/kumascript.py
- mdn/tests/test_kumascript.py
This is responsible for 20 [unknown_kumascript](https://browsercompat.herokuapp.com/importer/issues/unknown_kumascript) issues.
> fix bug 1198806 - Handle {{WebkitBug}}

- mdn/kumascript.py
- mdn/specifications.py
- mdn/tests/test_compatibility.py
- mdn/tests/test_kumascript.py
* Convert MDN relative links to absolute links
* Silently drop ``title`` attributes, ``class=external``, and ``class=external-icon``.
* Allow <a> tags in specification description
Fixes about 100 [tag_dropped](https://browsercompat.herokuapp.com/importer/issues/tag_dropped) issues and 50 [unexpected_attribute](https://browsercompat.herokuapp.com/importer/issues/unexpected_attribute) issues.
> bug 1198896 - Improve handling of <a> tags

- mdn/kumascript.py
- mdn/tests/test_kumascript.py
Used to translate a gecko version into Firefox, Thunderbird, SeaMonkey, and FXOS versions. Fixes about 80 [unknown_kumascript](https://browsercompat.herokuapp.com/importer/issues/unknown_kumascript) issues.
> fix bug 1187927 - Handle {{geckoRelease}}

- mdn/kumascript.py
- mdn/tests/test_compatibility.py
- mdn/tests/test_kumascript.py
- mdn/tests/test_specifications.py
Switch cross-reference macros to generate MDN links in text areas, and plain text in feature names.  Add handling for cross-reference macros used in compatibility data, responsible for about 150 [unknown_kumascript](https://browsercompat.herokuapp.com/importer/issues/unknown_kumascript) issues.
> Bug 1181140 - Handle cross-reference macros

- bcauth/tests.py
- mdn/tests/test_tasks.py
- mdn/tests/test_views.py
- requirements.txt
- webplatformcompat/tests/test_models.py
- webplatformcompat/tests/test_viewsets.py
Updating mock from 1.0.1 to 1.3.0 exposed that the tests of mocked calls were not using the assertion methods, and thus were not testing anything.
Part of getting system ready for [bug 1153288](https://bugzilla.mozilla.org/show_bug.cgi?id=1153288), with a goal of [bumping all requirements](https://github.com/mdn/browsercompat/tree/bump_requirements_1153288) and [getting to green](https://requires.io/github/mdn/browsercompat/requirements/?branch=bump_requirements_1153288)
> Update mock to 1.3.0

- mdn/migrations/0008_switch_modified_to_datetimefield.py
- mdn/models.py
- mdn/tests/test_models.py
- requirements.txt
- webplatformcompat/history.py
- webplatformcompat/migrations/0015_switch_created_modified_to_datetimefield.py
- webplatformcompat/tests/test_cache.py
Updating django_extensions from 1.5.5 to 1.5.7 included a change to ``ModificationDateTimeField`` and the ``CreationDateTimeField`` to make them more like the Django standard ``DateTimeField``.  This required a migration and code changes, so I took the opportunity to switch to Django's ``DateTimeField`` entirely.  It behaves differently, setting times on the DB rather than in Python, requiring some changes.
This is part of getting ready for [bug 1153288](https://bugzilla.mozilla.org/show_bug.cgi?id=1153288), with a goal of [bumping all requirements](https://github.com/mdn/browsercompat/tree/bump_requirements_1153288) and [getting to green](https://requires.io/github/mdn/browsercompat/requirements/?branch=bump_requirements_1153288)
> Update django_extensions to 1.5.7

- bcauth/helpers.py
- bcauth/templates/account/login.jinja2
- bcauth/templates/socialaccount/connections.jinja2
- requirements.txt
- wpcsite/settings.py
django-allauth 0.23.0 drops the context processors, which changes how the providers list is accessed.
> Update django-allauth to 0.23.0

- requirements.txt
- webplatformcompat/migrations/0016_feature_sections_allow_blank.py
- webplatformcompat/models.py
- webplatformcompat/serializers.py
- webplatformcompat/viewsets.py
DRF 3.2 makes a couple of changes that required code changes:
* In a many-to-many field, blank=False (default) now means that a blank result is not allowed.  Switch to blank=True to allow empty, remove non-standard extra args to feature.sections, and make a migration.
* ``request.QUERY_PARAMS`` changed to ``request.query_params``.
This is part of getting ready for [bug 1153288](https://bugzilla.mozilla.org/show_bug.cgi?id=1153288), with a goal of [bumping all requirements](https://github.com/mdn/browsercompat/tree/bump_requirements_1153288) and [getting to green](https://requires.io/github/mdn/browsercompat/requirements/?branch=bump_requirements_1153288).  Next is the last one, updates to Django 1.8
> Update Django REST Framework to 3.2.4

- tools/import_mdn.py
Some pages have the lethal combination of lots of compat data, many translations, and lots of data issues.  Because we don't have the async infrastructure in place, processing these pages takes longer than the requests timeout. This change still gives up after 3 tries, but continues to the next page rather than failing the import.
> Give up importing huge pages

- mdn/views.py
When regular rounding is used, sometimes the combined percentage is above 100% and the browser omits the final status bar (the green one!). This rounds the percentage down to the nearest 0.1%, which can leave unused space at the end, but doesn't omit any bars.
> fix bug 1208681 - Round down page percentages

- mdn/html.py
- mdn/tests/test_html.py
- mdn/tests/test_views.py
- mdn/views.py
- requirements.txt
This PR:
- Encodes all unicode strings as UTF-8 before passing to CSV writer
- Converts the BOM character (0xFEFF) to spaces in ``HTMLText``
The BOM character appears in [Web/CSS/-webkit-mask](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask) (In "Basic Support" row, between ``<td>{{CompatNo}}﻿`` and ``</td>``, see [importer](https://browsercompat.herokuapp.com/importer/3951)), and was causing Python's ASCII-only CSV writer to choke.  The issue CSV can now include unicode, and ``-webkit-mask`` doesn't warn about the BOM as inline text.
> bug 1208238 - Handle unicode in CSV

- mdn/compatibility.py
- mdn/data.py
- mdn/scrape.py
- mdn/tests/base.py
- mdn/tests/test_compatibility.py
- mdn/tests/test_data.py
- mdn/tests/test_scrape.py
- webplatformcompat/static/js/webplatformcompat.js
- webplatformcompat/templates/webplatformcompat/feature.basic.jinja2
- webplatformcompat/tests/test_view_serializers.py
Previously, "Basic support" rows were imported as child rows of the feature.  This PR changes these to describing the feature itself.
"Basic support" was used to test importing of child rows.  This is switched to a new test row, ``<code>contain</code> and <code>cover</code>``, another row on [Web/CSS/background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#Browser_compatibility).  The difference in text size means many issue spans changed.
The display code was updated to add a "Basic support" row with the supports for the subject feature.  Some same localizations are also provided.
> Treat "Basic support" rows as describing the feature

- tools/load_spec_data.py
This line in [Spec2](https://developer.mozilla.org/en-US/docs/Template:Spec2) was breaking tools/load_spec_data.py:
```
'Unhandled Promise Rejection': 'ED',
```
Adjust the regex to handle optional space in these lines.
> Handle changed whitespace in Spec2

- mdn/compatibility.py
- mdn/data.py
- mdn/tests/base.py
- mdn/tests/test_compatibility.py
- mdn/tests/test_data.py
- mdn/tests/test_scrape.py
The current browser names and slugs suggest that the desktop variants are the normal ones, and the mobile ones are the different ones.  [bug 1128525](https://bugzilla.mozilla.org/show_bug.cgi?id=1128525) changes this, so that "Firefox" (slug "firefox") becomes "Firefox for Desktop" (slug "firefox_desktop").  This is a three-part change:
1. This PR, which makes the importer handle current and new names and slugs
2. Once shipped, change the names and slugs in https://browsercompat.herokuapp.com
3. Remove the old name and slug handling from the importer.
> bug 1128525 - Adjust browser names and slugs

- mdn/helpers.py
- mdn/tests/test_helpers.py
- wpcsite/settings.py
The reparse button is useful when developing locally, to test changes in the parsing code.  In production, the right thing is almost always to reset the page to download the latest from MDN.
This commit shows the button when ``DEBUG=True`` and hides it when ``False``, unless overridden by environment variable ``MDN_SHOW_REPARSE``.
``Original commit was based on request hostname being localhost or 127.0.0.1.``
> bug 1181140 - Hide reparse button in production

- webplatformcompat/jinja2/webplatformcompat/feature-basic.html
- webplatformcompat/static/js/webplatformcompat.js
The string "current" is used to denote "this happened so long ago we're not sure when". Before bug 1160214, this was denoted with a blank version. This updates the display code to expect "current" instead of a blank version.
One page that uses version=current is transform-origin:
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin
https://browsercompat.herokuapp.com/view_feature/847
https://browsercompat.herokuapp.com/api/v1/view_features/847.html
> fix bug 1188503 - Handle "current" version status

- webplatformcompat/jinja2/webplatformcompat/base.html
- wpcsite/jinja2.py
Add the messages framework helpers to the native Jinja2 backend in Django 1.8.
> bug 1188498 - Add messages framework to jinja2

- webplatformcompat/renderers.py
- webplatformcompat/tests/test_view_serializers.py
In the rendered used by view_features, detect 404s and other errors and return the standard Django error page, instead of continuing to parse data and eventually failing with a 500 error.
> fix bug 1210436 - Handle 404s in view_feature HTML

- mdn/jinja2/mdn/feature_page_detail.html
- mdn/jinja2/mdn/feature_page_list.html
Improve bugs and usability issues found with the live, production deploy to https://browsercompat.herokuapp.com:
* "search by slug" needs to be a GET, or will fail with CSRF issue in production
* The Reparse button can be omitted when then environment is set to ``MDN_SHOW_REPARSE=0``. In this case, use a Reset instead of a Reparse after a Commit.
* When the user (which may be the anonymous user) can't perform the next action, suggest they Sign In as someone who can, rather than tell them there is nothing to do.
> bug 1208911 - "Next Action", round 2

- docs/raw/maturity-by-slug-response-body.json
- docs/raw/specification-revert-response-body.json
- docs/raw/view-features-list-response-body.json
- tools/integration_requests.py
- webplatformcompat/serializers.py
- webplatformcompat/tests/test_serializers.py
- webplatformcompat/view_serializers.py
Fix some API issues discovered in Madison, WI:
* ``tools/integration_requests.py --display --include-mod`` fails due to unicode->ASCII encoding issues
* Reverting a specification did not set the maturity to the old value
* The ``view_features`` list view displayed canonical features names as ``none``.
> bug 1153288 - More API fixes

- mdn/scrape.py
- mdn/tests/test_scrape.py
Fix a 500 error when importing a feature with unicode characters, such as this page:
"cubic-bezier() w/ ordinate ∉[0,1]"
* https://developer.mozilla.org/en-US/docs/Web/CSS/timing-function
* https://browsercompat.herokuapp.com/importer/840
> bug 1181140 - Handle unicode feature names

- webplatformcompat/models.py
- webplatformcompat/tests/test_models.py
In some cases (such as swapping each child pairs) it is necessary to reload both the previous and the next child from the database, so that the MPTT metadata is correct for the move.
> fix bug 1224341 - Fix Feature.set_children_order

- bcauth/tests.py
- requirements-dev.txt
- requirements.txt
- setup.cfg
- tox.ini
- webplatformcompat/jinja2/webplatformcompat/base.html
- webplatformcompat/jinja2/webplatformcompat/home.html
- webplatformcompat/pagination.py
- webplatformcompat/renderers.py
- webplatformcompat/tests/base.py
- webplatformcompat/tests/test_history.py
- webplatformcompat/tests/test_serializers.py
- webplatformcompat/tests/test_view_serializers.py
- webplatformcompat/tests/test_views.py
- webplatformcompat/tests/test_viewsets.py
- webplatformcompat/urls.py
- webplatformcompat/view_serializers.py
- wpcsite/settings.py
This PR bumps requirements to [latest versions](https://requires.io/github/mdn/browsercompat/requirements/?branch=update_reqs_1153288), including Django REST Framework 3.3 (which may enable a better browsable API eventually).
Then, it namespaces the v1 API views.  This has no effect outside the code, but will lay the foundation for  supporting a v2 API at the same time.
> Namespace v1 API, to prepare for v2 API

- mdn/jinja2/mdn/feature_page_detail.html
When running a long import, poll the server to see if the import is complete every second, instead of immediately after getting the last poll response (several times a second).
[Bug 1224381](https://bugzilla.mozilla.org/show_bug.cgi?id=1224381) is fixed - [Web/API/KeyboardEvent/key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) now [imports](https://browsercompat.herokuapp.com/importer/2519) - but it also attempts a denial-of-service attack while it is waiting for the parse to complete.
> fix bug 1224381 - Poll import every 1 second

- mdn/jinja2/mdn/feature_page_detail.html
- mdn/tests/test_views.py
The importer includes links to the API when the user can commit data, and the reverse is broken with namespaced API URLs. This adds a test to use a privileged user to fetch the view, and fixes the template to use namespaced API URLs.
> bug 1159406 - Fix importer for namespaced API

- mdn/jinja2/mdn/feature_page_detail.html
When the server is in async mode, change text after a successful sync, and start polling the server to reload with new data IDs.
Also, only set the handler for the commit button during page setup.
> fix bug 1124356 - Improve UI for async commit

- webplatformcompat/tests/v2/test_parsers.py
- webplatformcompat/tests/v2/test_viewsets.py
- webplatformcompat/v2/parsers.py
According to the [JSON API v1.0 spec](http://jsonapi.org/format/1.0/#crud), "The type member is required in every resource object throughout requests and responses". This PR makes it a parse error to omit it. The desired error is a [409 Conflict](http://jsonapi.org/format/1.0/#crud-creating-responses-409), and the error format is wrong, but those are covered by other bugs ([bug 1243217](https://bugzilla.mozilla.org/show_bug.cgi?id=1243217) and [bug 1242649](https://bugzilla.mozilla.org/show_bug.cgi?id=1242649)).
> bug 1243217 - Require type member in parser

- env.dist
- requirements.txt
- wpcsite/settings.py
Use [python-decouple](https://github.com/henriquebastos/python-decouple/) to standardize loading configuration from the environment, and [unipath](https://github.com/mikeorr/Unipath) to make path lookups nicer. Add a bunch of new configuration settings that can be overridden in the environment.
If you were using a ``.env`` file (not sure if anyone was), this changes the format of that file to the one that python-decouple likes.
> bug 1218237, others - Refactor and expand settings

- .gitignore
- tools/run_integration_tests.sh
- webplatformcompat/migrations/0001_initial.py
- wpcsite/settings.py
These changes were prompted by switching my development environment to use Python 3.5.1 an a ``.env`` file instead of pure environment variables.
Additional work from PR #94 (Refactor and expand settings):
* Ignore user environment files ``.env`` and ``settings.ini``.
* Add a ``USE_CACHE`` setting, to allow disabling the cache in integration tests, even when user environment files define cache connection variables.
Additional work from PR #95 (Python 3.5):
* Adjust initial migration to pretend we never used a byte sequence for a JSON default, instead of changing to a unicode string in migration 0010, so that tests will run under Python 3.5.1.
> Bug fixes from 1218237, 1238587

- webplatformcompat/routers.py
- webplatformcompat/tests/test_viewsets.py
- webplatformcompat/v1/viewsets.py
- webplatformcompat/v2/viewsets.py
- webplatformcompat/viewsets.py
[bug 1229783](https://bugzilla.mozilla.org/show_bug.cgi?id=1229783) is about a 500 error when using a string ID instead of a integer ID. This is because the code was trying to accept any ID string, so that an integer ID or a slug could be passed, as part of [bug 1078699](https://bugzilla.mozilla.org/show_bug.cgi?id=1078699).
This code changes this behavior:
* expands ``GroupedRouter.get_urls()``, so the code has more control over the generated paths,
* sets the viewset's PK pattern to accept only integer IDs (``r'\d+'``, so that string IDs will return a 404,
* adds the ability to declare an ``alternate_lookup`` viewset method, which can be used with an alternate ID pattern,
* converts viewfeature's views from using ``get_object_or_404`` to ``alternate_lookup`` for looking up features by …
> fix bug 1229783 - require integer IDs 

- MANIFEST.in
``make sdist`` QA checks fail because this folder isn't in MANIFEST.in
> bug 1246192 - Add templatetags to MANIFEST.in

- docs/v1/change-control.rst
- docs/v1/doc_cases.json
- docs/v1/raw/user-me-anon-request-headers.txt
- docs/v1/raw/user-me-anon-response-body.json
- docs/v1/raw/user-me-anon-response-headers.txt
- docs/v1/raw/user-me-authenticated-request-headers.txt
- docs/v1/raw/user-me-authenticated-response-headers.txt
- docs/v2/doc_cases.json
- docs/v2/raw/user-me-anon-request-headers.txt
- docs/v2/raw/user-me-anon-response-body.json
- docs/v2/raw/user-me-anon-response-headers.txt
- docs/v2/raw/user-me-authenticated-request-headers.txt
- docs/v2/raw/user-me-authenticated-response-headers.txt
- docs/v2/resources.rst
- tools/integration_requests.py
- webplatformcompat/tests/test_viewsets.py
- webplatformcompat/tests/v1/base.py
- webplatformcompat/tests/v1/test_viewsets.py
- webplatformcompat/tests/v2/test_viewsets.py
- webplatformcompat/v1/viewsets.py
- webplatformcompat/v2/viewsets.py
- webplatformcompat/viewsets.py
Add "reflection" endpoints of ``/api/v1/users/me`` and ``/api/v2/users/me``, that clients (such as the [C&M](https://github.com/mdn/browsercompat-cm) interface) can use to check the validity of credentials and get the details of the authenticated user. Updates unit and integration tests, documentation.
> bug 1159354 - Add /api/v#/users/me endpoint

- tools/mirror_mdn_features.py
The [$children API](https://developer.mozilla.org/en-US/docs/Web/CSS/display$children) is used by ``mirror_mdn_features.py`` to find deeply-nested MDN pages, especially in the JavaScript topic. However, deleted docs will occasionally appear in the list of children, and ``$children`` will be called on the deleted doc, which returns this JSON:
```json
{"error": "Document does not exist."}
```
If the ``$children`` JSON doesn't at least have a 'url' key, then warn and continue with the next URL.
> fix bug 1247842 - Detect deleted docs

- docs/v1/raw/user-by-id-response-body.json
- docs/v1/raw/user-by-username-response-body.json
- docs/v2/raw/changeset-related-user-response-body.json
- docs/v2/raw/user-by-id-response-body.json
- docs/v2/raw/user-by-username-response-body.json
- webplatformcompat/__init__.py
- webplatformcompat/apps.py
- webplatformcompat/models.py
- webplatformcompat/signals.py
- webplatformcompat/tests/test_models.py
- webplatformcompat/tests/test_signals.py
- webplatformcompat/tests/v1/test_viewsets.py
- webplatformcompat/tests/v2/test_viewsets.py
Refactor signals from models.py into signals.py, and be more explicit about signal registration order and associated models. Then, add a new signal to invalidate the user's instance cache when a new changeset is created, so that it will immediately be added to the relationship section. This changes a handful of integration tests.
> fix bug 1247690 - Changeset invalidates user instance cache

- webplatformcompat/routers.py
301 redirect [/api/v1/browsers/](http://browsercompat.herokuapp.com/api/v1/browsers/) to [/api/v1/browsers](http://browsercompat.herokuapp.com/api/v1/browsers). This worked (with a 302 redirect) before the switch to namespaced v1/v2 API URLs, but gives currently gives 410 Gone.
> fix bug 1250976 - Redirect to slashless API URLs

- tools/run_integration_tests.sh
- webplatformcompat/migrations/0018_add_resources_table.py
- webplatformcompat/migrations/0019_add_reference_permissions.py
Add the references table and related resources, but without the related Django model changes. Also add API permissions for the new references instances.
This PR needs to be applied in production before merging code that uses the new table. This PR is step 1 of 3:
* [Step 2](https://github.com/mdn/browsercompat/tree/references_step2_1216786): Switch code to use references instead of feature/section M2M relationship
* [Step 3](https://github.com/mdn/browsercompat/tree/references_step3_1216786): Drop unused database data
> bug 1216786 - Prepare database for references

- requirements/application.txt
- webplatformcompat/migrations/0021_drop_feature_section_m2m.py
- webplatformcompat/models.py
* Drop M2M relation from features to sections
* Drop note from Section
* Disallow null references list in HistoricalFeatures
django-sortedm2m needs to be retained until migrations are squashed.
> fix bug 1216786 - Cleanup transition to references

- docs/v1/doc_cases.json
- docs/v1/raw/browser-create-in-changeset-2-request-headers.txt
- docs/v1/raw/view-feature-update-parts-with-changeset-2-request-headers.txt
- docs/v1/raw/view-feature-update-parts-with-changeset-3-request-headers.txt
- docs/v2/doc_cases.json
- docs/v2/implementation.rst
- docs/v2/raw/browser-create-in-changeset-2-request-headers.txt
- docs/v2/raw/browser-create-in-changeset-2-response-body.json
- docs/v2/raw/view-feature-update-parts-with-changeset-2-request-headers.txt
- docs/v2/raw/view-feature-update-parts-with-changeset-2-response-body.json
- docs/v2/raw/view-feature-update-parts-with-changeset-3-request-headers.txt
- docs/v2/raw/view-feature-update-parts-with-changeset-3-response-body.json
- tools/client.py
- webplatformcompat/exceptions.py
- webplatformcompat/history.py
- webplatformcompat/tests/test_exceptions.py
- webplatformcompat/tests/test_history.py
- webplatformcompat/tests/v1/test_history.py
- webplatformcompat/tests/v1/test_viewsets.py
- webplatformcompat/tests/v2/test_history.py
- webplatformcompat/tests/v2/test_viewsets.py
- webplatformcompat/v2/renderers.py
- webplatformcompat/v2/viewsets.py
- wpcsite/settings.py
JSON API v1.0 requires that a 400 error is returned when certain query parameters are used. This includes parameters for unimplemented features (like [``include``](http://jsonapi.org/format/1.0/#fetching-includes)), as well as any all-lowercase query parameters (reserved for [future growth](http://jsonapi.org/format/1.0/#query-parameters)).
This PR adds query parameter verification, returning [correctly formatted error objects](http://jsonapi.org/format/1.0/#error-objects) for rejected parameters.
The existing parameter ``changeset`` is invalid under the JSON API v1.0 spec. It is used to perform related modifications under the same logical changeset. This PR changes the parameter to ``use_changeset``, which is reflected in unit test, tools, integration tests, and documentation.
> fix bug 1243221 - Reject query parameters reserved by JSON API v1.0

- CONTRIBUTING.rst
- HISTORY.rst
- README.rst
- docs/entrypoints.rst
- docs/installation.rst
- docs/issues.rst
- docs/services.rst
- docs/technologies.rst
- docs/tools.rst
- docs/v1/intro.rst
- docs/v2/intro.rst
- requirements/development.txt
The BrowserCompat API project has been abandoned since March 2016.  We're removing the beta integration from MDN, closing bugs as WONTFIX, and updating the docs.
> Cancelling the project
